services:
  backend:
    build:
      context: ./expressjs-and-rest-sri-nivas1227
    ports:
      - "5000:5000"
    networks:
      - app-net
  frontend:
    build:
      context: ./source-code
      args:
        REACT_APP_BACKEND_URL: "http://localhost:5000"
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-net

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - frontend-build:/usr/share/nginx/html:ro
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - app-net
networks:
  app-net:
