services:
  backend:
    build:
      context: ./expressjs-and-rest-sri-nivas1227
    ports:
      - "5000:5000"
    networks:
      - app-net

  nginx:
    build:
      context: ./source-code
      args:
        REACT_APP_BACKEND_URL:
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
